# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  webAppName: 'test'
  serviceConnection: 'cnt'
  azureSubscriptionId: '7c71b563-0dc0-4bc0-bcf6-06f8f0516c7a'
  loadTestResource: 'radhikatest-az'
  loadTestResourceGroup: 'radhika-test'
  location: 'EAST US'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16'
  displayName: 'Install Node.js'
- task: b61b360c-31ac-4389-922b-303ea8befde7@1
  inputs:
    azureSubscription: 'cnt-test'
    loadTestConfigFile: 'test/customerIssue.yaml'
    resourceGroup: 'radhika-test'
    loadTestResource: '- task: AzureLoadTest@1
    env: |
      [
      {
        "name":"LoginTenant",
        "value":"$(TenantId)"
      },
      {
        "name":"ClientId",
        "value":"$(ClientId)"
      },
      {
        "name":"Secret",
        "value":"$(OneLakeAdminIntegrationTestsAppSecret)"
      },
      {
        "name":"Host",
        "value":"$(oneLakeHost)"
      },
      {
        "name":"Workspace",
        "value":"$(Workspace)"
      },
      {
        "name":"Artifact",
        "value":"$(Artifact)"
      },
      {
        "name":"api",
        "value":"$(api)"
      },
      {
        "name":"PbiApi",
        "value":"$(PbiApi)"
      },
      {
        "name":"PBIHost",
        "value":"$(PBIHost)"
      },
      {
        "name":"PBIClientId",
        "value":"$(PBIClientId)"
      },
      {
        "name":"PBIUserName",
        "value":"$(PBIUserName)"
      },
      {
        "name":"PBIPassword",
        "value":"$(onelakeppetenantadmin)"
      },
      {
        "name":"ServicePrincipalOneLakeIntegartionTests",
        "value":"$(ClientObjectId)"
      },
      {
      "name":"Port",
      "value":"443"
      },
      {
      "name":"FolderPath",
      "value":"Files"
      },
      {
      "name":"FolderName",
      "value": "perfTest1"
      },
      {
      "name": "Users",
      "value":"1"
      },
      {
      "name":"LoopCount",
      "value":"500"
      },
      {
      "name":"UploadFileName",
      "value": "4MB.bin"
      },
      {
      "name":"FileSize",
      "value": "4000000"
      },
      {
      "name":"LoginHost",
      "value":"login.windows-ppe.net"
      },
      {
      "name":"ResourceScope",
      "value":"https://storage.azure.com"
      },
      {
      "name":"CredGrantType",
      "value":"client_credentials"
      },
      {
      "name":"FileName",
      "value":"test"
      },
      {
      "name":"fileNameconfig",
      "value": "none"
      },
      {
      "name": "TestingType",
      "value":"individual"
      },
      {
      "name":"UseCounter",
      "value":"0"
      },
      {
      "name":"chunkCount",
      "value":2
      },
      {
      "name":"TestRunId",
      "value":"test"
      },
      {
      "name":"responseMD5",
      "value":"89d6842b4ac5656feaaa065f5b383961"
      }
      ]'
